-- 10_create_tables.sql
-- Create schema objects for Smart Fertilizer Recommendation System

CREATE TABLE farmer (
  farmer_id   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  farm_name   VARCHAR2(100) NOT NULL,
  location    VARCHAR2(100)
);

CREATE TABLE lab_user (
  user_id   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  username  VARCHAR2(50) UNIQUE NOT NULL,
  role      VARCHAR2(30)
);

CREATE TABLE soil_test (
  soil_id    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  farmer_id  NUMBER NOT NULL,
  lab_user_id NUMBER NOT NULL,
  nitrogen   NUMBER CHECK (nitrogen >= 0),
  phosphorus NUMBER CHECK (phosphorus >= 0),
  potassium  NUMBER CHECK (potassium >= 0),
  test_date  DATE DEFAULT SYSDATE,
  CONSTRAINT fk_soil_farmer FOREIGN KEY (farmer_id) REFERENCES farmer(farmer_id),
  CONSTRAINT fk_soil_user   FOREIGN KEY (lab_user_id) REFERENCES lab_user(user_id)
);

CREATE TABLE fertilizer (
  fertilizer_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  fertilizer_name VARCHAR2(50) UNIQUE NOT NULL,
  nutrient_type VARCHAR2(20) NOT NULL,
  recommended_amount NUMBER
);

CREATE TABLE recommendation (
  rec_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  soil_id NUMBER NOT NULL,
  fertilizer_id NUMBER,
  recommendation_text VARCHAR2(4000),
  rec_date DATE DEFAULT SYSDATE,
  approved_by NUMBER,
  CONSTRAINT fk_rec_soil FOREIGN KEY (soil_id) REFERENCES soil_test(soil_id),
  CONSTRAINT fk_rec_fert FOREIGN KEY (fertilizer_id) REFERENCES fertilizer(fertilizer_id)
);

CREATE TABLE audit_log (
  audit_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  username VARCHAR2(50),
  operation VARCHAR2(20),
  object_type VARCHAR2(30),
  object_id NUMBER,
  attempt_time TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP,
  status VARCHAR2(20),
  message VARCHAR2(4000)
);

CREATE TABLE holiday (
  holiday_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  holiday_date DATE UNIQUE NOT NULL,
  description VARCHAR2(200)
);
